#Inventaritems
default cockpitKeycard = InventoryItem("inv_keycard", "Schlüsselkarte", "Schrankverwalter\nProfessor Eich\n13.05.1978")

default key_L = InventoryItem("inv_key_L", "Taste", "Buchstabe L\n16 21	8 8")
default key_I = InventoryItem("inv_key_I", "Taste", "Buchstabe I\n19 15")
default key_N = InventoryItem("inv_key_N", "Taste", "Buchstabe N\n22 9 5 12 5")
default key_U = InventoryItem("inv_key_U", "Taste", "Buchstabe U\n1 21 6 7 1 2 5 14 0")
default key_X = InventoryItem("inv_key_X", "Taste", "Buchstabe X\n8	15 6 6 5 14 20 12 9 3 8")
default key_W1 = InventoryItem("inv_key_W", "Taste", "Buchstabe W\n19 3 8 1 6 6 5 14")
default key_W2 = InventoryItem("inv_key_W", "Taste", "Buchstabe W\n23 9 18")
default key_D = InventoryItem("inv_key_D", "Taste", "Buchstabe D\n1 12 12 5 19 0")
default key_O = InventoryItem("inv_key_O", "Taste", "Buchstabe O\n1 21 6 0")
default key_S = InventoryItem("inv_key_S", "Taste", "Buchstabe S\n7 21 20 5 19")
default key_P = InventoryItem("inv_key_P", "Taste", "Buchstabe P\n7 5 12 9 14 7 5 14")
default key_E = InventoryItem("inv_key_E", "Taste", "Buchstabe E\n0	0 0")
default key_R = InventoryItem("inv_key_R", "Taste", "Buchstabe R\n5 9 14")
default monitor_sw = InventoryItem("inv_monitor_sw", "Bildschirm", "Schwarz-Weiß Display")
default monitor_color = InventoryItem("inv_monitor_color", "Bildschirm", "Farbdisplay")
default micro = UsableItem("inv_mic", "Modul", "Mikrofon", "UseMic")
default gpsModule = UsableItem("inv_gps", "Modul", "GPS", "UseGPS")
default speaker = UsableItem("inv_speaker", "Modul", "Lausprecher", "UseSpeaker")
default camera = UsableItem("inv_cam", "Modul", "Kamera", "UseCam")
default wlanModule = UsableItem("inv_wlanmodul", "Modul", "WLAN", "UseWLAN")

default Kopfhoerer = InventoryItem("inv_kopfhoerer", "Gegenstand","Kopfhörer")
